server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front-end
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /selectMenus/**
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/storeOrders/**, 
        - id: rider
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**, 
        - id: Payment Gateway
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: history
          uri: http://localhost:8086
          predicates:
            - Path=, /histories/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front-end
          uri: http://frontEnd:8080
          predicates:
            - Path=/orders/**, /selectMenus/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/storeOrders/**, 
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/notifications/**, 
        - id: Payment Gateway
          uri: http://paymentGateway:8080
          predicates:
            - Path=, 
        - id: history
          uri: http://history:8080
          predicates:
            - Path=, /histories/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
